### PR TITLE
Action Sounds Fixes #40

### LINKED ISSUE #40: Add action sound effects
The game would be a lot more fun with audio. In-game sound effects will be needed when the player AND enemy does the following:

* Attack
* Risk Attack
* Heal

Make sure to credit where you get the sound effects from in the source code and in the readme!

### PR DESCRIPTION
**Pull request by kevinmmurphy**

### CODE REVIEW

**Comment by tagniam** [comment]
This is so cool 👍 Is there any way to have a few different sounds for attack, then play one of them randomly when the player attacks? This makes it less repetitive, but if it's too difficult then this is ok.

Also, is there an alternative for the healing sound effect? I was thinking something more fantasy-rpg, like the ones in this video https://www.youtube.com/watch?v=BXfk4QtMkG8. The current one sounds more suitable for an fps.

**Comment by kevinmmurphy** [comment]
Sure, my idea would be to have to attack sounds be linked to the amount of
damage dealt.  This way a player gets both variation in sound, and
information on how much damage they deal. (The text feedback is a bit
fast). I can do that if you like. (Not tonight)
-Kevin

**Comment by tagniam** [comment]
Sounds good to me, no rush. Suggestion: when a player does 0 damage, a `whoosh` sound effect is played (which means a miss).

**Comment by kevinmmurphy** [comment]
Great idea! Will do.
-Kevin

**Comment by kevinmmurphy** [comment]
Sound variation added. Includes miss and crit. If you want to have different sounds per class that is possible too. (e.g. magic user casts spells rather than fights with swords)

**Comment by tagniam** [comment]
Did you happen to find an alternate heal sound?

**Comment by kevinmmurphy** [comment]
No, I can look later and change the file.
-Kevin

**Comment by kevinmmurphy** [comment]
Heal sound changed.

**Comment by tagniam** [comment]
Thanks for implementing a major feature! Great work, the code design will make it easy for extension later on.

**Comment by kevinmmurphy** [comment]
It was fun!

**Pull request merged**
