### PR TITLE
Added the bomb sound effect

### PR DESCRIPTION
**Pull request by LaloCode**
Please test these changes and tell me if it works, for some reason no sound effects work for me and all I hear is the windows error sound 😢

### CODE REVIEW

**Comment by tagniam** [comment]
Works for me on Linux, how did you run the game? Through visual studio?

**Comment by LaloCode** [comment]
Yep, I followed the getting started section and I'm using visual studio

When I click the run button from visual studio I get this 

image

Finding the .exe file makes the game work but I get no sound effects, also in the solution the ALL_BUILD project gets skipped: 

image

I don't know if that is inteneded but I tried not skipping ALL_BUILD and the result is the same

I also tried changing the CMake platform to Win32 but again, still no sounds

image

I really have no idea why this could be happening I also built the binaries in a separate build folder inside Turn

**Comment by tagniam** [comment]
I'm not sure what's going on with your Visual Studio config, but if you move the `Turn.exe` executable to the `Turn` folder, the sounds should work - the problem is that currently we don't embed the game sounds in the executable, so the program expects a `sounds` folder in the same directory to pull the sound files from. Could you check if that works?

**Comment by LaloCode** [comment]
Yep, that was the issue all sound effects now work including the bomb 👍

**Comment by tagniam** [comment]
LGTM, thanks for the contribution! Thanks also for reminding me that we need to start embedding sound files, I'll be creating another issue for that.

**Pull request merged**
