### PR TITLE
User names with spaces

### LINKED ISSUE #4: Allow for names with spaces
On the first run, the user has to set the player name. Unfortunately the player name will not include characters after a space in the name. So if you enter `John Doe` as the player name, the name will be saved as `John`.

### PR DESCRIPTION
**Pull request by IgorAntun**
Now uses string::getline() so usernames can have spaces.
Closes #4

### CODE REVIEW

**Comment by IgorAntun** [comment]
Should work now, can you check please?

**Comment by tagniam** [comment]
Hmm, I can enter a name now but the name still can't have spaces, and now there's a weird bug where all the values after the name in the `data.txt` file is 0. Is this happening on your machine as well?

**Comment by IgorAntun** [comment]
Since I'm on Linux, I removed the unecessary stuff and kept only the setup/file writing related parts.
It's working normally for me here, but since I'm unable to run the full version, I might be missing something.

What I'm running: https://hastebin.com/gapoduviwu.cpp
Saved file: https://hastebin.com/gekiliwayu (Input: class "4", name "Igor Antun")

**Comment by tagniam** [comment]
After a bit of debugging I've found the problem. After saving the player data correctly to `data.txt`, an `ifstream` is used to read the data from that file [here](https://github.com/tagniam/Turn/blob/master/Turn/src/Player.cpp#L29), but `getline` should be used instead so that a name with spaces will be read correctly.

**Comment by tagniam** [comment]
Fixed by #42

**Pull request closed without merging**
