### PR TITLE
Add new enemy types Vampire, Werewolf, Goblin and Gargoyle.

### PR DESCRIPTION
**Pull request by ilimugur**
Contributes to resolving #50 . Also, introduces an EnemyType enum. That way, Enemy class really becomes an abstract class and each class inheriting from Enemy is made to overload the GetType() member method, in an effort to keep the EnemyType enum up-to-date.

### CODE REVIEW

**Comment by ilimugur** [comment]
Seems to build and run in Windows with no problems. Feel free to comment on the EnemyType enum (and turning Enemy class to an abstract one) by the way. It's a little hacky, but I believe it would help keep track of different types of enemies, and get rid of the use of magic number in enemy creation. (i.e. rand() % NUM_TYPES_OF_ENEMIES, right before the switch case statement that creates an enemy)

**Comment by ilimugur** [comment]
Umm, okay. I'll resolve the conflicts in a few minutes.

**Comment by ilimugur** [comment]
Updated my modifications to include the updates to the original repository.

**Comment by tagniam** [comment]
Thanks for the contribution! Sorry for the delay, I'll look this over later today

**Comment by tagniam** [comment]
Thanks a lot for redesigning the enemy generation. Originally I never intended for the game to have this many enemies, so that's why the original code is pretty hacky. Enums make it a lot more organized and readable.

**Comment by ilimugur** [comment]
Glad I could help.

**Pull request merged**
