### PR TITLE
Add shop greeting messages

### PR DESCRIPTION
**Pull request by Mego**
Implements #63 

Shop greetings are stored in a `std::vector` in `StoreGreetings.h`, which can be easily expanded as needed. `random_greeting` uses C++11 random library features to return a random greeting from the `std::vector`.

### CODE REVIEW

**Comment by tagniam** [comment]
Hi @Mego, does this build successfully on your machine? Travis CI is encountering build errors for some reason.

**Comment by Mego** [comment]
The issue is tangentially related to my edits - there is a function prototype in `Common.h` that takes a `std::string` as an argument, but `string` is not `#include`d in `Common.h`. It only works in other compilation units because of the order of the `#include` statements. I'll make a commit to fix that.

**Comment by tagniam** [comment]
I'm getting a runtime error which outputs the following and crashes the game:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

To replicate this, enter the store and keep entering selections. Eventually the game crashes. Tested on Linux.

**Comment by Mego** [comment]
It looks like the exception occurred as a result of a mistake on my part - I mistakenly wrote the random choice code as if `std::uniform_int_distribution(a, b)` returned `int`s from the range `[a, b)` (like the equivalent `random.randrange` in Python), when in fact it returns from the range `[a, b]`. The latest commit should fix the error.

**Comment by tagniam** [comment]
Yeah, that fixed it. Thanks for helping out! My favorite message is "We're happy to separate you from your money!".

**Pull request merged**
