### PR TITLE
Introduction to EnemyType Slimeball

### PR DESCRIPTION
**Pull request by Darctalus**
Contributing a new enemy type to open source.

### CODE REVIEW

**Comment by tagniam** [comment]
Hi, before I merge this, the `etSlimeball` case must be added to the `Game::SetEnemy()` method.

**Comment by Darctalus** [comment]
I am pretty sure that should work.  What am I not seeing here?

**Comment by tagniam** [comment]
You also need to include the slimeball header file in `EnemyTypes.h`, sorry I didn't notice that originally

**Comment by tagniam** [comment]
Thanks for contributing!

**Pull request merged**
